#!/bin/bash
set -euo pipefail

export HUD_USER="hud"
export HUD_PREFIX="/opt/hud"
export HUD_BIN_DIR="/usr/bin"
export HUD_UNIT_DIR="/usr/lib/systemd/system"
export HUD_CONFIG_DIR="/etc"
export HUD_DATA_DIR="/usr/share"
export HUD_APPS_DIR="${HUD_PREFIX}/apps"
export HUD_APPS_CATALOG="${HUD_PREFIX}/apps/catalog.json"

source "${HUD_DATA_DIR}/logging.sh"

ctl_command="hudctl-$1"

if ! which "${ctl_command}" > /dev/null; then
    log_fatal "Unknown command $1"
fi

{ 
    if ! flock -n 9; then
        log_fatal "Could not obtain lock"
    fi

    "${ctl_command}" "${@:2}"
} 9>/var/lock/.hudctl