#!/bin/bash
set -euo pipefail
source "${HUD_DATA_DIR}/logging.sh"
source "${HUD_DATA_DIR}/json.sh"

# APP_BUNDLE is a tar (possibly gz compressed) file
# Structure:
# manifest.json -- app metadata & file listing
# binaries/
#    ...app binaries
# units/
#    ...systemd unit files
# scripts/
#    ...post_deploy scripts
# configs/
#    ...app configs
# data/
#    ...app resources/static data

# Install process
# If app is not already installed, or installed and disabled:
# - Create app folder
# - Rsync contents of bundle to app folder
# - Add new catalog entry for app

# If app is enabled:
# - Compare manifest bundle and app folder
# - Unlink any files that are being removed
# - Rsync contents of bundle to app folder
# - hudctl-enable app

APP_BUNDLE="$1"

BUNDLE=$(mktemp -d)
tar -xaf "${APP_BUNDLE}" -C "${BUNDLE}"
trap "rm -rf ${BUNDLE}" EXIT

BUNDLE_MANIFEST="${BUNDLE}/manifest.json"
if [ ! -f "${BUNDLE_MANIFEST}" ]; then
    log_red "Bundle does not contain a manifest"
    exit 1
fi

BUNDLE_NAME="$(json_query_file "${BUNDLE_MANIFEST}" '.name')"
APP_INSTALL_DIR="${HUD_APPS_DIR}/${BUNDLE_NAME}"

function sync_bundle() {
    BUNDLE_ROOT=$1
    INSTALL_ROOT=$2

    log_section "Syncing bundle files"
    mkdir -p "${INSTALL_ROOT}"
    rsync -ap --chown="${HUD_USER}:${HUD_USER}" \
          --delete "${BUNDLE_ROOT}/" \
          "${INSTALL_ROOT}"
    chmod 755 "${INSTALL_ROOT}" 
}

function unlink_removed_files() {
    # Unlink any files that will be removed when the new bundle is installed
    BUNDLE_FOLDER="${1}"
    LINKED_FOLDER="${2}" # System folder that these files are linked to
    OLD_MANIFEST="${3}"
    NEW_MANIFEST="${BUNDLE_MANIFEST}"

    OLD_FILES="$(jq -Mcr \
                    --arg section "${BUNDLE_FOLDER}" \
                    '.[$section] // []' \
                    "${OLD_MANIFEST}" )"

    NEW_FILES="$(jq -Mcr \
                    --arg section "${BUNDLE_FOLDER}" \
                    '.[$section] // []' \
                    "${NEW_MANIFEST}" )"

    
    REMOVED_FILES_JSON="$(json_array_difference "${OLD_FILES}" "${NEW_FILES}")"
    json_array_into REMOVED_FILES "${REMOVED_FILES_JSON}"
    
    if (( ${#REMOVED_FILES[@]} != 0 )); then
        log_section "Unlinking removed ${BUNDLE_FOLDER}"
        for removed_file in "${REMOVED_FILES[@]}"; do
            full_path="${LINKED_FOLDER}/${removed_file}"

            log_action "unlink" "${full_path}"

            if [ ! -f "${full_path}" ]; then
                log_failure "${full_path} does not exist!"
            fi

            unlink "${full_path}"
        done
    fi
}

if hudctl-catalog "${BUNDLE_NAME}" >/dev/null; then
    log_section "Reinstalling ${BUNDLE_NAME}"
    
    if [ "$(hudctl-catalog "${BUNDLE_NAME}" get enabled)" == "true" ]; then
        # If the app is already enabled, we first need to unlink any files 
        # that don't exist in the new bundle
        APP_MANIFEST="$(hudctl-catalog "${BUNDLE_NAME}" get manifest)"
        unlink_removed_files "binaries" "${HUD_BIN_DIR}" "${APP_MANIFEST}"
        unlink_removed_files "units" "${HUD_UNIT_DIR}" "${APP_MANIFEST}"
        unlink_removed_files "configs" "${HUD_CONFIG_DIR}" "${APP_MANIFEST}"
        unlink_removed_files "data" "${HUD_DATA_DIR}" "${APP_MANIFEST}"

        sync_bundle "${BUNDLE}" "${APP_INSTALL_DIR}"
        hudctl-enable "${BUNDLE_NAME}"

    else
        # If the app is disabled, we don't want to renable it 
        sync_bundle "${BUNDLE}" "${APP_INSTALL_DIR}"
    fi
else
    # App not installed
    log_section "Installing ${BUNDLE_NAME}"

    sync_bundle "${BUNDLE}" "${APP_INSTALL_DIR}"
    hudctl-catalog "${BUNDLE_NAME}" new "${APP_INSTALL_DIR}/manifest.json"

    # This should be temporary, or put behind a flag
    hudctl-enable "${BUNDLE_NAME}"
fi