#!/bin/bash
set -euo pipefail
source "${HUD_DATA_DIR}/logging.sh"

APP_NAME="$1"
if ! hudctl-catalog "${APP_NAME}" >/dev/null; then
    log_fatal "App ${APP_NAME} does not exist"
fi

APP_MANIFEST_PATH="$(hudctl-catalog "${APP_NAME}" get manifest)"
APP_ROOT="$(dirname "${APP_MANIFEST_PATH}")"

# Export all variables starting with APP_
export $(compgen -A variable | grep 'APP_*')
export -p | grep 'declare -x APP_*'
