#!/bin/bash
set -euo pipefail

source "${HUD_DATA_DIR}/logging.sh"


OUTPUT="$(jq -n '{"root": [], "boot": {}}')"

function add_partition() {
    UBOOT_VAL="$1"

    OUTPUT="$(
        echo "${OUTPUT}" | \
        jq -M \
           --arg u "${UBOOT_VAL}" \
           --arg d "${HR_BLOCK_DEVICE}p${UBOOT_VAL}" \
           '.root += [{"uboot": $u, "device": $d}]'
    )"
}

function add_boot_partition() {
    OUTPUT="$(
        echo "${OUTPUT}" | \
        jq -M \
           --arg d "${HR_BLOCK_DEVICE}p1" \
           '.boot = {"device": $d}'
    )"
}

function set_current_partition() {
    CURRENT_PARTITION="$(fw_printenv "${HR_UBOOT_VAR}" | cut -d'=' -f2)"

    OUTPUT="$(
        echo "${OUTPUT}" | \
        jq -M \
           --arg c "${CURRENT_PARTITION}" \
           '.root |= map(if (.uboot == $c) then (.current = true) else (.current = false) end)'
    )"
}


add_partition "${HR_ROOT_PART_A}"
add_partition "${HR_ROOT_PART_B}"
add_boot_partition
set_current_partition


echo "${OUTPUT}" | jq -M '.'