BCC_VERSION = 0.26.0
BCC_SITE = $(call github,iovisor,bcc,v$(BCC_VERSION))
BCC_INSTALL_STAGING = YES
BCC_INSTALL_TARGET = YES
BCC_CONF_OPTS = -DCMAKE_USE_LIBBPF_PACKAGE=ON -DENABLE_LIBDEBUGINFOD=OFF -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF
BCC_DEPENDENCIES = xz clang llvm libbpf host-pkgconf

define BCC_LINUX_CONFIG_FIXUPS
	$(call KCONFIG_ENABLE_OPT,CONFIG_BPF)
	$(call KCONFIG_ENABLE_OPT,CONFIG_BPF_SYSCALL)
	$(call KCONFIG_ENABLE_OPT,CONFIG_BPF_JIT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_HAVE_BPF_JIT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_HAVE_EBPF_JIT)
	$(call KCONFIG_ENABLE_OPT,CONFIG_BPF_EVENTS)
	$(call KCONFIG_ENABLE_OPT,CONFIG_IKHEADERS)
endef

$(eval $(cmake-package))