#!/usr/bin/env bash
#-NoHelp: Internal
#-Help: Export the current buildroot configuration to hudos_defconfig
#-Extended: All sensitive keys (wifi settings, etc) will be removed
set -euo pipefail

source "${HB_LIB_DIR}/logging.sh"

pushd "${HB_BUILDROOT_DIR}"
make savedefconfig BR2_DEFCONFIG="${HB_BUILDROOT_GIT_CONFIG}"
popd

# These settings should not be saved to git
sed -i '/^BR2_PACKAGE_HUDOS_NETWORK_WIFI_/d' "${HB_BUILDROOT_GIT_CONFIG}"
sed -i '/^BR2_PACKAGE_HUDOS_DEPLOY_USER/d' "${HB_BUILDROOT_GIT_CONFIG}"

touch "${HB_BUILDROOT_GIT_CONFIG}" "${HB_BUILDROOT_CONFIG}"