#!/usr/bin/env bash
#-NoHelp: Internal
set -euo pipefail
source "${HB_LIB_DIR}/logging.sh"

# Has buildroot been setup?
if [ ! -f "${HB_BUILDROOT_DIR}/.hbstamp" ]; then
    if [ ! -d "${HB_BUILDROOT_DIR}" ]; then
        # Force vendor to download dependencies
        rm -f "${HB_VENDOR_DIR}/.stamp"
        # If the directory doesn't exist, we need to download buildroot
        hb-vendor
    fi

    # Apply our custom defconfig
    # At somepoint we'll need to support multiple defconfigs
    hb-buildroot-build "$(basename "${HB_BUILDROOT_GIT_CONFIG}")"
fi
touch "${HB_BUILDROOT_DIR}/.hbstamp"