#!/usr/bin/env bash
#-Help: Upload latest rootfs to device
#-Use: [<device_name>]
#-Extended: If non-default device is used, it's deploy key will be built into the image first
set -euo pipefail
source "${HB_LIB_DIR}/logging.sh"

# TODO: Which key is built into the image?
device_name="${1:-}"
if [[ "${device_name}" != "" ]]; then
    log_fatal "building image with a different device is not supported yet"
    device="$(hb-devices list "${device_name}" )"
else
    device="$(hb-devices default)"
fi
device_private_key="$(json_query_blob "${device}" '.keys.private')"
device_host="$(json_query_blob "${device}" '.host')"

buildroot_rootfs="${HB_BUILDROOT_IMAGES_DIR}/rootfs.ext4"
if [ ! -f "${buildroot_rootfs}" ]; then
    log_fatal "No rootfs found. Have you ran buildroot?"
fi

gzip -c "${buildroot_rootfs}" | pv | ssh \
     -o StrictHostKeychecking=no \
     -o UserKnownHostsFile=/dev/null \
     -o PreferredAuthentications=publickey \
     -i "${device_private_key}" \
     "deploy@${device_host}" \
     "sudo hudctl root upgrade"