#!/usr/bin/env bash
#-Help: Wraps buildroot to include custom packages
set -euo pipefail
source "${HB_LIB_DIR}/logging.sh"

export HB_BUILDROOT_DIR="${HB_VENDOR_DIR}/buildroot"
export HB_BUILDROOT_CONFIG="${HB_BUILDROOT_DIR}/.config"
export HB_BUILDROOT_EXTERNAL_TREE="${HB_REPOSITORY_DIR}/buildroot/br2_hudos"
export HB_BUILDROOT_GIT_CONFIG="${HB_BUILDROOT_EXTERNAL_TREE}/configs/hudos_defconfig"
export HB_BUILDROOT_BUILD_DIR="${HB_BUILDROOT_DIR}/output/build"
export HB_BUILDROOT_IMAGES_DIR="${HB_BUILDROOT_DIR}/output/images"
export HB_BUILDROOT_TARGET_DIR="${HB_BUILDROOT_DIR}/output/target"

cmd="${1:-}"
if [[ "${cmd}" == "" ]]; then
    log_warning "No command given"
    exit 0
fi

hb-buildroot-configure

if [ "${HB_BUILDROOT_GIT_CONFIG}" -nt "${HB_BUILDROOT_CONFIG}" ]; then
    log_warning "Defconfig has been updated by git!"
    log_fatal "Either reset buildroot (erasing any changes), or merge your changes into the new config" 
fi

buildroot_command="hb-buildroot-$cmd"
if ! which "${buildroot_command}" > /dev/null; then
    log_fatal "Unknown command $cmd"
fi

"${buildroot_command}" "${@:2}"

if [ "${HB_BUILDROOT_CONFIG}" -nt "${HB_BUILDROOT_GIT_CONFIG}" ]; then
    read -p "Do you want to save buildroot config to git? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        hb-buildroot-save
    fi
fi