#!/usr/bin/env bash
#-Help: SSH into device as deploy user
#-Use: [<device-name>]
set -euo pipefail
source "${HB_LIB_DIR}/json.sh"

device_name="${1:-}"
if [[ "${device_name}" != "" ]]; then
    shift 1
fi

if [[ "${device_name}" != "" ]]; then
    device="$(hb-devices list "${device_name}" )"
else
    device="$(hb-devices default)"
fi
device_private_key="$(json_query_blob "${device}" '.keys.private')"
device_host="$(json_query_blob "${device}" '.host')"

ssh -o StrictHostKeychecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o PreferredAuthentications=publickey \
    -i "${device_private_key}" \
    "deploy@${device_host}"